### ISSUE TITLE
Impossible to log in to page in order to open a support ticket

### ISSUE THREAD

**Issue by maxfenv** [eu-cdse/documentation#170] opened 2023-06-19 12:29 UTC
I have a registered account with 'dataspace.copernicus.eu'.  I have successfully created some oauth credentials and used the SeninelHub API using those.

I'm now trying to request some s3 credentials. According to the documentation I have to open a support ticket to do so.  When I click on the Submit a request I am told that I should login first. When I click on the presented login link I am redirected back to the same page. I can never reach the login page.

**Comment by maxfenv** [comment] 2023-06-19 12:31
I should say that this is happening on both a QtWebEngine based browser and in Firefox 114.0.1 (64-bit)

**Comment by Pratichhya** [comment] 2023-06-20 13:15
@maxfenv We would like to apologise for the inconvenience you faced. Our team will quickly look into the issue of logging in and respond to you as soon as possible.

**Comment by Pratichhya** [comment] 2023-06-20 13:37
@maxfenv we weren't able to reproduce the issue, could you please try again.

**Comment by Pratichhya** [comment] 2023-06-21 09:53
@maxfenv, we found a similiar issue for user using Firefox. The reason was due to the strict prefernces set for the browser. Maybe you can reconsider changing the prefernces and testing it again. 

I hope this helps and hereby close the issue.

**Closed by Pratichhya** 2023-06-21 09:53 UTC

**Comment by maxfenv** [comment] 2023-06-22 07:54
Well I managed to submit a support request.  The behaviour of the page is still somewhat strange, after login, the login button is still displayed. Clicking it again after having logged in just reloads the page. However submitting a request did work, after having changed the 'Enhanced Tracking Protection' in firefox to 'Standard'. Something something third party cookies?
